---

- name: Prepare admin users and group
  hosts: all
  become: true

  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Read admin_vars from file
      ansible.builtin.include_vars:
        file: admin_vars.yml
        name: admin_vars

    - name: Create ansible admin_group
      ansible.builtin.group:
        name: "{{ admin_vars.admin_group }}"
        state: present

    - name: Provide passwordless sudo rights to admin_group
      community.general.sudoers:
        name: allow-admin_users
        group: "{{ admin_vars.admin_group }}"
        state: present
        nopassword: true
        commands: ALL

    - name: Create ansible admin_users
      ansible.builtin.user:
        name: "{{ item }}"
        shell: /bin/bash
        update_password: always
        password: '!'
        groups: "{{ admin_vars.admin_group }}"
        append: true
      with_items:
        - "{{ admin_vars.admin_users }}"

    - name: Add authorized key
      ansible.posix.authorized_key:
        user: "{{ item }}" 
        state: present
        key: "{{ lookup('file', '~/.ssh/ansible.pub') }}" 
      with_items:
        - "{{ admin_vars.admin_users }}"
