---

- name: Clean admin users and groups
  hosts: homelab
  become: true

  tasks:
    - name: Read users from file
      ansible.builtin.include_vars:
        file: admin_vars.yml
        name: admin_vars

    - name: Remove group from sudoers
      community.general.sudoers:
        name: allow-admin_users
        state: absent

    - name: Remove admin group
      ansible.builtin.group:
        name: "{{ admin_vars.admin_group }}"
        state: absent

    - name: Remove admin users
      ansible.builtin.user:
        name: "{{ item }}"
        state: absent
      with_items:
        - "{{ admin_vars.admin_users }}"
